#!/usr/bin/env node

import { program } from 'commander';
import { Ladda } from './src/ladda.js';
import path from 'path';

function ladda() {
  console.log(`ladder: ${program.opts().ladder}`);
  return new Ladda(path.resolve(import.meta.dirname, 'data', program.opts().ladder + '.json'));
}

program
  .name('ladda')
  .option('-l, --ladder <laddername>', 'the ladder being loaded or modified', 'junior')
  .description('simple ladder tournament generator');

program.command('d')
  .description('dump db on to screen')
  .action(() => {
    ladda().dumpDb();
  });

program.command('i')
  .description('wipe and reinitialize the db')
  .action(() => {
    ladda().initDb();
  });

program.command('p')
  .description('add a player')
  .argument('<name>', 'player name')
  .action((new_name, options) => {
    ladda().addPlayer(new_name);
  });

program.command('m')
  .description('add a match')
  .argument('<winner>', 'winner name')
  .argument('<loser>', 'loser name')
  .action((winner, loser, options) => {
    ladda().addMatch(winner, loser);
  });

program.parse();
